### ISSUE TITLE
adalo publish not working on windows

### ISSUE THREAD

**Issue by wstoettinger** [AdaloHQ/docs#53]
Hi,
the adalo publish command is currently not working on windows. 
There is a problem with the mkdir command to create the dist directory structure (mkdir -p is not supported on windows).

The second problem I ran into after fixing the previous one was with the way how the paths are constructed in the build.js. 
The problem is, that the path in editor.js and runtime.js end up as '..\..\index.js' without escaping the backslashes.
they should either be '..\\..\\index.js' or '../../index.js' both of which are working.

with those changes I was able to publish a component to adalo on windows.

I think this should be updated for compatibility.

**Comment by scott-massey** [comment]
We were able to resolve this on another platform, this is all good now.
