### ISSUE TITLE
`Was this page helpful` doesn't work

### ISSUE THREAD

**Issue by SpencerKaiser** [AdaloHQ/docs#57]
On any page within the Adalo docs, the buttons to submit your feedback don't seem to do anything

Browser: Safari `Version 15.2 (17612.3.6.1.6)`
OS: MacOS `12.1 (21C52)`

**Comment by scott-massey** [comment]
Hi Spencer,

This repo is actually for our developer documentation (developers.adalo.com), but I've let our education lead know about this.

Best,
Scott Massey
Software Engineer @Adalo

**Comment by scott-massey** [comment]
Our education lead has let me know that the issue actually has to do with our docs provider, GitBook, and we don't have any control over it.

**Comment by SpencerKaiser** [comment]
Oof if that's the case, yall should probably remove them ☹️ I'll close this though since it's not the right repo for that set of docs
