### ISSUE TITLE
Notifications docs are missing rate limit info

### ISSUE THREAD

**Issue by SpencerKaiser** [AdaloHQ/docs#58]
The page for the [notifications API](https://help.adalo.com/integrations/the-adalo-api/push-notifications) doesn't have any information on rate limiting... I'm just going to guess based on the other endpoints that it's 5/second, but yall need to update that page!

**Comment by scott-massey** [comment]
Hi Spencer,

This repo is actually for our developer documentation (developers.adalo.com), but I've let our education lead know about this.

Best,
Scott Massey
Software Engineer @Adalo

**Comment by SpencerKaiser** [comment]
Ah alright... do yall not maintain the docs for the Notifications API as well?

**Comment by scott-massey** [comment]
We do maintain `help.adalo.com`, if that's what you're talking about. Our education lead is planning to update the docs with the rate limiting info.
